### ISSUE TITLE
Django documentation params

### ISSUE THREAD

**Issue by luzik** [pavlov99/json-rpc#111]
https://json-rpc.readthedocs.io/en/latest/django_integration.html

What is:
```
@api.dispatcher.add_method
def my_method(request, *args, **kwargs):
    return args, kwargs
```

What I have to use:
```
@api.dispatcher.add_method
def my_method(*args):
    return args
```

1. `kwargs` are only as args last element
2. `request` is method first param, not django request
3. can't implement `@login_required` decorator to json-rpc call

**Comment by pavlov99** [comment]
Hi, @luzik , I did not get your question. Could you paraphrase, please?

**Comment by luzik** [comment]
All based on your documentation:

```
@api.dispatcher.add_method
def my_method(request, *args, **kwargs):
    return args, kwargs
```


Ad. 1

I assumed that mixed args and kwargs rpc params should be translated into python args and kwargs like:

`{'jsonrpc': '2.0', 'method': 'my_method', 'params': ['one', 'two', {'a': 4}], 'id': 5}`

into:

```
args=['one', 'two']
kwargs={'a': 4}
```

but your code gives

```
[['two', {'a': 4}], {}]
```

Ad. 2

```
{'jsonrpc': '2.0', 'method': 'my_method', 'params': ['one', 'two'], 'id': 6}
```

gives

```
[['two'], {}]
```

where is 'one' ???


Ad. 3
Is there any way I can use https://docs.djangoproject.com/en/3.0/topics/auth/default/#the-login-required-decorator with @api.dispatcher.add_method ?

**Comment by pavlov99** [comment]
Thank you for your example, let me clarify some points here:

json-rpc 2.0 as a protocol accepts either args or kwargs but not both at the same time. In your first example the correct parsing should result in
```python
args=['one', 'two', {'a': 4}]
kwargs={}
```
so the code should return
```python
[['one', 'two', {'a': 4}], {}]
```

An example with kwargs would be
```
{
  'jsonrpc': '2.0',
  'method': 'my_method',
  'params': {
    'one': 'one',
    'two': 'two',
    'my_dict': {'a': 4}
  },
  'id': 5
}
```

Your second example is very similar to the first one. In both of them, the first argument is missing. Let me examine those further.

Lastly, decorators like `login-required` should be applicable to views as before. `@api.dispatcher.add_method` just register the function with api handler to pull it by name later. It does not know how this function was created and whether it uses decorators or not. The way to go should be:
```python
from django.contrib.auth.decorators import login_required

@api.dispatcher.add_method
@login_required
def my_view(request):
    return "my code here"
```

The reason why this request exists with Django backend is because it's the way views work in the framework: `request` is expected.

**Comment by luzik** [comment]
Thank you for explanation. You are right about json-rpc 2.0.

I believe that fixing #2 (passing request variable from jsonrpc.backend.django view to method) will fix decorators like @login_required.

I also figured out that commit  https://github.com/pavlov99/json-rpc/commit/e5c05343cec23d020da03e0f1dfa7ee635bd939a#diff-279c3165c1125bfb9baf68ee7b61702d is not released yet and it is related to this issue

**Comment by pavlov99** [comment]
In fact, I believe this commit fixes the issue. Without it, the first argument (`"one"` in your example) is assigned to `request` variable of `my_method`.

I've just released [1.12.3](https://pypi.org/project/json-rpc/1.12.3/) with the fix. Hope it helps your case.

**Comment by MattFisher** [comment]
@pavlov99 I don't think this should have been a patch-level version bump. It's going to break every existing deployed use of this package in Django projects that have methods with positional arguments.

Yes, it's a bug fix that brings behaviour in line with the documentation, but it's going to break working systems.

**Comment by pavlov99** [comment]
@MattFisher you are right! It was a premature decision on my side. I removed 1.12.3 from pypi and shall release 1.13.0 within 24h.

**Comment by pavlov99** [comment]
[1.13.0](https://pypi.org/project/json-rpc/1.13.0/) released.
