### ISSUE TITLE
Chat api 

### ISSUE THREAD

**Issue by csselo** [pavlov99/json-rpc#41]
Hi

I want to make a simple chat server with this api but it is staighless how can I send a interrupt to the client for fetching messages?

if I use "always check" data, it become harmful for the server

any ideas?

**Comment by pavlov99** [comment]
Hi, @csselo . Could you push messages from the server instead of long pulling them the client? It is possible to use web sockets for that kind of tasks.

If you would like to interrupt execution from client side, you could send interrupt message (another api call), so server would not push result. To do that, on task creation in the queue, server should return task id, such as one from `celery`. Then using that task id you could remove it from the queue.

**Comment by csselo** [comment]
thank u
